# Generated by Django 5.0.6 on 2024-11-09 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=6)),
                ('value', models.FloatField(blank=True, null=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional_app.parameter')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional_app.region')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional_app.year')),
            ],
            options={
                'unique_together': {('region', 'parameter', 'year', 'season')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=3)),
                ('value', models.FloatField(blank=True, null=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional_app.parameter')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional_app.region')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional_app.year')),
            ],
            options={
                'unique_together': {('region', 'parameter', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='AnnualData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_value', models.FloatField(blank=True, null=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional_app.parameter')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional_app.region')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional_app.year')),
            ],
            options={
                'unique_together': {('region', 'parameter', 'year')},
            },
        ),
    ]
