# Generated by Django 5.1.3 on 2024-11-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regional_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': '01 Region'},
        ),
    ]
